name: Secure Scan

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "21 4 * * *"
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  pull-requests: write
  security-events: write

jobs:
  secureci:
    uses: TangoisdownHQ/TID-SecureCI/.github/workflows/tid-secureci.yml@b14b7066dfb5137e1aab10405aa0f0e08bfe3b4d
    secrets: inherit
    with:
      enforce: true
      fail_severity: HIGH,CRITICAL
